### ISSUE TITLE
郵便番号ごとの住所データを json で出力する

### ISSUE THREAD

**Issue by itigoore01** [jp-postal-code/address-data-generator#1]
# Specification

CLI で動作確認にする。
`adg generate api [output dir]  --pretty`

以下のディレクトリ構成で出力を行う。 
`{郵便番号上3桁}/{郵便番号下4桁}.json`

JSONは以下のフォーマットで出力する。

```json
[
  {
    "postalCode": "1000001",
    "regionId": 13,
    "region": "東京都",
    "locality": "千代田区",
    "address1": "千代田",
    "address2": "",
    "regionKana": "トウキョウト",
    "localityKana": "チヨダク",
    "address1Kana": "チヨダ",
    "address2Kana": ""
  }
]
```

# Tasks

- [x] ken-all.zip を tmp にダウンロード
  - [x] ステータスコード2xx以外なら終了する
- [x] ken-all.zip を tmp に解凍
- [x] KEN-ALL.CSV をパースする
- [ ] 郵便番号をキーとしたMap<string, Address[]> に変換する
  - [ ] カナは全角カタカナにする
  - [ ] Address は regionId, localityKana, address1, address2 の昇順でソートする
- [ ] 郵便番号ごとに Address[] の JSON を出力する
  - [ ] pretty オプションが有効な場合は整形して出力する
